# numpy

In [3]:
import numpy as np
vector=np.array([5,10,15,20])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vector)
print(matrix)
print(vector.shape)
print(matrix.shape)

[ 5 10 15 20]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(4,)
(3, 3)


In [5]:
#索引、切片(0开头)
a=matrix[1,2]
b=matrix[:,1]
c=vector[0:2]
d=matrix[2,:]
print(a);print(b);print(c);print(d)


6
[2 5 8]
[ 5 10]
[7 8 9]


In [9]:
#提取y为某一值时的个体所有数据
matrix=np.array([[5,10,15,0],[20,25,35,1],[15,6,10,0]])
y0=(matrix[:,3]==0)
print(y0)
train0=matrix[y0,:]
print(train0)

[ True False  True]
[[ 5 10 15  0]
 [15  6 10  0]]


In [11]:
#与或
vector=np.array([5,10,15,20])
equal=(vector==10)&(vector==5)
equal2=(vector==10)|(vector==5)
print(equal);print(equal2)

[False False False False]
[ True  True False False]


In [19]:
#对数组整个数字类型进行改变
vector=np.array(['1','2','3'])
print(vector.dtype)
print(vector)
vector=vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [18]:
#计算（详见书）
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix.min())
print(matrix.max())
print(matrix.sum())
print(matrix.sum(axis=1))#每行各求和,0为每列各求和

1
9
45
[ 6 15 24]


In [21]:
#对向量进行变换
print(np.arange(15))
a=np.arange(15).reshape(3,5)#3行5列
b=np.array(np.arange(15))
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
#对矩阵的常见处理
print(np.zeros((3,4)))
np.ones((2,3,4),dtype=np.int32)#三维数组

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [37]:
#arange
print(np.arange(10,30,5))
print(np.arange(1,10,1).reshape(3,3))

[10 15 20 25]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
#生成随机数矩阵
print(np.random.random((2,3)))#随机取
from numpy import pi
np.linspace(0,2*pi,100)#均匀间隔取

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [41]:
#矩阵的计算
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A*B)
print(A.dot(B))
print(np.dot(A,B))
C=np.exp(A)
D=np.sqrt(B)
print(C)
print(D)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[2.71828183 2.71828183]
 [1.         2.71828183]]
[[1.41421356 0.        ]
 [1.73205081 2.        ]]


In [46]:
a=np.floor(10*np.random.random((3,4)))#floor向下取整
print(a)
print(a.ravel())#将矩阵按行拉成一个向量
a.shape=(6,2)#拉直成向量后变换形态
print(a)
print(a.T)#转置


[[4. 8. 2. 9.]
 [1. 8. 2. 1.]
 [9. 0. 3. 4.]]
[4. 8. 2. 9. 1. 8. 2. 1. 9. 0. 3. 4.]
[[4. 8.]
 [2. 9.]
 [1. 8.]
 [2. 1.]
 [9. 0.]
 [3. 4.]]


In [47]:
#拼接
a=np.floor(10*np.random.random((2,2)))
b=np.floor(10*np.random.random((2,2)))
print(a)
print(b)
print(np.hstack((a,b)))#横着拼
print(np.vstack((a,b)))#竖着拼

[[2. 5.]
 [3. 6.]]
[[9. 7.]
 [5. 6.]]
[[2. 5. 9. 7.]
 [3. 6. 5. 6.]]
[[2. 5.]
 [3. 6.]
 [9. 7.]
 [5. 6.]]


In [49]:
#分割
a=np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a,3))#横着切分成3份
print(np.hsplit(a,(3,4)))#在横着第三个数前切一刀，在4前切一刀
b=a.T
print(b)
print(np.vsplit(b,4))

[[7. 4. 1. 2. 3. 9. 6. 1. 8. 0. 4. 4.]
 [5. 9. 9. 9. 8. 2. 0. 0. 0. 5. 8. 9.]]
[array([[7., 4., 1., 2.],
       [5., 9., 9., 9.]]), array([[3., 9., 6., 1.],
       [8., 2., 0., 0.]]), array([[8., 0., 4., 4.],
       [0., 5., 8., 9.]])]
[array([[7., 4., 1.],
       [5., 9., 9.]]), array([[2.],
       [9.]]), array([[3., 9., 6., 1., 8., 0., 4., 4.],
       [8., 2., 0., 0., 0., 5., 8., 9.]])]
[[7. 5.]
 [4. 9.]
 [1. 9.]
 [2. 9.]
 [3. 8.]
 [9. 2.]
 [6. 0.]
 [1. 0.]
 [8. 0.]
 [0. 5.]
 [4. 8.]
 [4. 9.]]
[array([[7., 5.],
       [4., 9.],
       [1., 9.]]), array([[2., 9.],
       [3., 8.],
       [9., 2.]]), array([[6., 0.],
       [1., 0.],
       [8., 0.]]), array([[0., 5.],
       [4., 8.],
       [4., 9.]])]


In [55]:
a=np.arange(12)
b=a
b.shape=3,4
print(a.shape)
print(id(a));print(id(b))

#view--a,c共用了一套值，即c中的值改变，a也会变，但c的形态变了，a不会变
c=a.view()
c.shape=(2,6)
print(a.shape)
print(a)
c[0,4]=1234
print(a)

#复制（a与d无影响关系）
d=a.copy()
d[0,0]=12345
print(a)

(3, 4)
261080723584
261080723584
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [56]:
#查找每行/每列的最大值/最小值
data=np.sin(np.arange(20)).reshape(5,4)
print(data)
ind=data.argmax(axis=0)#每列最大的值对应的索引
print(ind)
data_max=data[ind,range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [58]:
#扩展
a=np.arange(0,40,10)
print(a)
b=np.tile(a,(2,3))#行扩大2倍，列扩大3倍
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [63]:
#排序
a=np.array([[4,3,5],[1,2,1]])
print(a)
b=np.sort(a,axis=1)
print(b)
a.sort(axis=0)
print(a)

c=np.array([4,3,1,2])
j=np.argsort(c)#返回从小到大值的索引
print(j)
print(c[j])

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
[[1 2 1]
 [4 3 5]]
[2 3 1 0]
[1 2 3 4]
